# set global prefix as ctrl+w
set-option -g prefix C-w

# easy config reload while in tmux session (use prefix 'ctrl+w' then 'r')
# you'll see a quick "tmux.conf reloaded." msg on bottom
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# enable mouse mode (use your mouse to click on splits and resize them)
set -g mouse on

# use alt+arrow-keys to move between splits
bind -n M-left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# split windows with 'v' vertical and 'h' horizontal (after prefix)
bind-key v split-window -h
bind-key h split-window -v

# use shift+arrow-keys to switch between windows
bind -n S-Left previous-window
bind -n S-Right next-window

# reorder windows with ctrl+shift+arrow-keys
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

